# Your Website Title
title: ZIDONG
# Your Website URL
url: 'https://zidong6344.github.io/'

# Leave it default
baseurl: '' 

# Google Analytics
ga_index: UA-XXXXXXXX-X
ga_cv: UA-XXXXXXXX-X

# Index page and Profile Information
name: 王子栋
tagline: 软件开发, 嵌入式开发, 优化算法
pic: touxiang.jpg # profile.png can be found at /assets/images/profile.png
description: 软件开发, 嵌入式开发, 优化算法
description_tiny: '故乡: 山西晋城 | 学校: 北京工业大学 | 学位: 硕士'
email: 542852426@qq.com
website: zidong6344.github.io # do not add http://
github: zidong6344


# Files or folders to be excluded
exclude: [gitbook_source_code/]

# All the plugins for Jekyll
plugins:
  - jekyll-sitemap
  - wdm
